# Generated by Django 4.2.26 on 2025-11-30 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.CharField(choices=[('DATASET_QUALITY', 'Dataset Quality Scores'), ('RULE_FREQUENCY', 'Rule Run Frequency'), ('RULES_PER_DATASET', 'Rules per Dataset'), ('RECENT_EXECUTIONS', 'Recent Rule Executions')], max_length=20)),
                ('data', models.JSONField(help_text='Graph data in JSON format')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userdashboardpreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userdashboardpreference',
            name='dashboard_config',
        ),
        migrations.RemoveField(
            model_name='userdashboardpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='DashboardConfiguration',
        ),
        migrations.DeleteModel(
            name='UserDashboardPreference',
        ),
        migrations.AddIndex(
            model_name='dashboardgraph',
            index=models.Index(fields=['graph_type', 'created_at'], name='dashboard_d_graph_t_ea051c_idx'),
        ),
    ]
