# Generated by Django 4.2.26 on 2025-11-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read'), ('RUN', 'Run'), ('TRIAGE', 'Triage'), ('EXPORT', 'Export')], max_length=20),
        ),
    ]
