# Generated by Django 4.2.26 on 2025-11-30 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('NOT_NULL', 'NOT_NULL'), ('UNIQUE', 'UNIQUE'), ('IN_RANGE', 'IN_RANGE'), ('FOREIGN_KEY', 'FOREIGN_KEY')], max_length=20)),
                ('dsl_expression', models.TextField(help_text="DSL expression like NOT_NULL('column_name')")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='datasets.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RuleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(help_text='Unique identifier for this rule execution', max_length=100, unique=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('passed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('sample_evidence', models.JSONField(blank=True, help_text='Sample evidence rows that failed', null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='rules.rule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
