# Generated by Django 4.2.26 on 2025-11-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
    ]
