# Generated by Django 4.2.26 on 2025-11-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_rulerun_dataset_rulerun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulerun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
