# Generated by Django 4.2.26 on 2025-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_rulerun_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('NOT_NULL', 'NOT_NULL'), ('UNIQUE', 'UNIQUE'), ('IN_RANGE', 'IN_RANGE'), ('FOREIGN_KEY', 'FOREIGN_KEY'), ('REGEX', 'REGEX'), ('LENGTH_RANGE', 'LENGTH_RANGE')], max_length=20),
        ),
    ]
