# Generated by Django 4.2.26 on 2025-11-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_alter_rule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulerun',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
    ]
