# Generated by Django 4.2.26 on 2025-12-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_rulerun_total_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('MISSING_VALUE', 'Missing Value Check'), ('DUPLICATE_DETECTION', 'Duplicate Detection'), ('OUTLIER_DETECTION', 'Outlier Detection'), ('SCHEMA_VALIDATION', 'Schema Validation'), ('CUSTOM', 'Custom Template')], max_length=30)),
                ('dsl_template', models.TextField(help_text='DSL template with placeholders like {column_name}')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
